### ISSUE TITLE
ConcurrentModificationException on load-in while developing datapack

### ISSUE THREAD

**Issue by dreamlibrarian** [daedalus4096/PrimalMagick#193]
Working with trying to generate a datapack for PrimalMagick and have experienced the below a couple times while reloading or starting a single player instance with an updated datapack post-startup.

Impact is user disconnection, and so far I've mitigated by opening the world again from the same client session, suggesting it's some kind of race condition.

I'll provide more detail if I can reproduce further.

```
[22Sep2023 20:41:08.345] [Netty Local Client IO #0/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
[22Sep2023 20:41:08.601] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: dreamlibrarian[local:E:8e75bd19] logged in with entity id 209 at (67.76826687905545, 63.0, 12.308770362563111)
[22Sep2023 20:41:08.950] [Render thread/INFO] [Inventory Profiles Next/]: [Inventory Profiles Next] Loaded 0 external GUI hints
[22Sep2023 20:41:08.950] [Render thread/INFO] [Inventory Profiles Next/]: [Inventory Profiles Next] Loaded 783 build-in GUI hints
[22Sep2023 20:41:08.951] [Render thread/INFO] [Inventory Profiles Next/]: [Inventory Profiles Next] Effective GUI hints after merge: 783
[22Sep2023 20:41:08.954] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: dreamlibrarian joined the game
[22Sep2023 20:41:09.058] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingIn
[22Sep2023 20:41:09.058] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from DISABLED to ENABLED
[22Sep2023 20:41:09.076] [Render thread/INFO] [com.verdantartifice.primalmagick.common.affinities.AffinityManager/]: Updated 57 enchantment_bonus affinity definitions
[22Sep2023 20:41:09.076] [Render thread/INFO] [com.verdantartifice.primalmagick.common.affinities.AffinityManager/]: Updated 38 potion_bonus affinity definitions
[22Sep2023 20:41:09.076] [Render thread/INFO] [com.verdantartifice.primalmagick.common.affinities.AffinityManager/]: Updated 110 entity_type affinity definitions
[22Sep2023 20:41:09.076] [Render thread/INFO] [com.verdantartifice.primalmagick.common.affinities.AffinityManager/]: Updated 724 item affinity definitions
[22Sep2023 20:41:09.078] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 29 research entries for discipline runeworking
[22Sep2023 20:41:09.078] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 42 research entries for discipline manaweaving
[22Sep2023 20:41:09.078] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 31 research entries for discipline alchemy
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 17 research entries for discipline scans
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 34 research entries for discipline sorcery
[22Sep2023 20:41:09.078] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 8
	Listeners:
		0: HIGHEST
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@36bd69e9 builtinMobSpawnBlocker(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		2: HIGH
		3: ASM: net.minecraftforge.common.ForgeInternalHandler@36bd69e9 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		4: NORMAL
		5: net.minecraftforge.eventbus.EventBus$$Lambda$5031/0x0000009001ccdcb8@38736000
		6: ASM: class vectorwing.farmersdelight.common.event.CommonEvents onAnimalsJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		7: ASM: net.orcinus.overweightfarming.events.MobEvents@40ef8b5e onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		8: ASM: class com.verdantartifice.primalmagick.common.events.PlayerEvents playerJoinEvent(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		9: ASM: journeymap.common.events.forge.ForgeServerEvents@3abb9a5c onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$ValueIterator.next(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at TRANSFORMER/primalmagick@4.0.3-23-gfb62c82.dirty/com.verdantartifice.primalmagick.common.research.ResearchEntries.getAllEntries(ResearchEntries.java:48)
	at TRANSFORMER/primalmagick@4.0.3-23-gfb62c82.dirty/com.verdantartifice.primalmagick.common.research.ResearchEntry.getKnownRecipeIds(ResearchEntry.java:310)
	at TRANSFORMER/primalmagick@4.0.3-23-gfb62c82.dirty/com.verdantartifice.primalmagick.common.crafting.recipe_book.ArcaneRecipeBookManager.syncRecipesWithResearch(ArcaneRecipeBookManager.java:87)
	at TRANSFORMER/primalmagick@4.0.3-23-gfb62c82.dirty/com.verdantartifice.primalmagick.common.events.PlayerEvents.playerJoinEvent(PlayerEvents.java:442)
	at TRANSFORMER/primalmagick@4.0.3-23-gfb62c82.dirty/com.verdantartifice.primalmagick.common.events.__PlayerEvents_playerJoinEvent_EntityJoinLevelEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:842)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:834)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:215)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Unknown Source)

[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 35 research entries for discipline ritual
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 24 research entries for discipline basics
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.research.ResearchLoader/]: Updated 27 research entries for discipline magitech
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.theorycrafting.ProjectTemplateLoader/]: Updated 22 theorycrafting project templates
[22Sep2023 20:41:09.079] [Render thread/INFO] [com.verdantartifice.primalmagick.common.runes.RuneEnchantmentDefinitionLoader/]: Updated 57 rune enchantment definitions
[22Sep2023 20:41:09.079] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:?]
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source) ~[?:?]
	at com.verdantartifice.primalmagick.common.research.ResearchEntries.getAllEntries(ResearchEntries.java:48) ~[primalmagick-4.0.3-23-gfb62c82.dirty.jar%23200!/:4.0.3-23-gfb62c82.dirty]
	at com.verdantartifice.primalmagick.common.research.ResearchEntry.getKnownRecipeIds(ResearchEntry.java:310) ~[primalmagick-4.0.3-23-gfb62c82.dirty.jar%23200!/:4.0.3-23-gfb62c82.dirty]
	at com.verdantartifice.primalmagick.common.crafting.recipe_book.ArcaneRecipeBookManager.syncRecipesWithResearch(ArcaneRecipeBookManager.java:87) ~[primalmagick-4.0.3-23-gfb62c82.dirty.jar%23200!/:4.0.3-23-gfb62c82.dirty]
	at com.verdantartifice.primalmagick.common.events.PlayerEvents.playerJoinEvent(PlayerEvents.java:442) ~[primalmagick-4.0.3-23-gfb62c82.dirty.jar%23200!/:4.0.3-23-gfb62c82.dirty]
	at com.verdantartifice.primalmagick.common.events.__PlayerEvents_playerJoinEvent_EntityJoinLevelEvent.invoke(.dynamic) ~[primalmagick-4.0.3-23-gfb62c82.dirty.jar%23200!/:4.0.3-23-gfb62c82.dirty]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:842) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:834) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23203!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[22Sep2023 20:41:09.082] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: dreamlibrarian lost connection: Invalid player data
[22Sep2023 20:41:09.082] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: dreamlibrarian left the game
```

**Comment by daedalus4096** [comment]
This *should* be fixed now.  Let me know if you run into it again.  Thanks!
