### ISSUE TITLE
Put enchanted ink and quill into the research table and it disappeared immediately. And the server console throw out errors.

### ISSUE THREAD

**Issue by ColdTearsYY** [daedalus4096/PrimalMagick#278]
crash report: https://mclo.gs/fLm8Kpu
version: 1.20.1

> [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
> net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
> 	Primal Magick (primalmagick) has failed to load correctly
> §7java.lang.NoClassDefFoundError: net/minecraft/world/inventory/RecipeCraftingHolder
> ]
> 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.2.20.jar%23846!/:?] {}
> 	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23846!/:?] {}
> 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
> 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23846!/:?] {}
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23846!/:?] {}
> 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23846!/:?] {}
> 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.20-universal.jar%23850!/:?] {re:classloading}
> 	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?] {re:classloading,pl:accesstransformer:B}
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%23103!/:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%23103!/:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%23103!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2389!/:?] {}
> 	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:46) ~[arclight-forge-1.20.1-1.0.6-SNAPSHOT.jar:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {}
> 	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:13) ~[arclight-forge-1.20.1-1.0.6-SNAPSHOT.jar:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
> 	at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) ~[arclight-forge-1.20.1-1.0.6-SNAPSHOT.jar%2383!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {}
> 	at io.izzel.arclight.server.Launcher.main(Launcher.java:18) ~[arclight-forge-1.20.1-1.0.6-SNAPSHOT.jar%2383!/:arclight-1.20.1-1.0.6-SNAPSHOT-52ab6e5] {}

**Comment by daedalus4096** [comment]
I see that you're trying to run MC 1.20.1 with version 4.1.1 of Primal Magick. That version of PM is meant to be used with version 1.20.2 of Minecraft. There are often significant differences in the Minecraft codebase, even in minor patches of the game. Do you encounter this error on the supported version as well?

**Comment by ColdTearsYY** [comment]
I tried this version because I encountered a bug on 4.0.9. Similar to https://github.com/daedalus4096/PrimalMagick/issues/241
I test it now and give you more additional information

**Comment by ColdTearsYY** [comment]
[10:41:04 ERROR] [Jade]: Caught unhandled exception : [null] java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.ordinal()" because "face" is null
[10:41:04 ERROR] [Jade]: See JadeErrorOutput.txt for more information
[10:41:06 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@25544e78, suppressing error
net.minecraft.ReportedException: Container click
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenuMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3406) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.network.protocol.PacketUtils.md8fbd51$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2075) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.ordinal()" because "face" is null
        at com.verdantartifice.primalmagick.common.tiles.devices.ResearchTableTileEntity.getInventoryIndexForFace(ResearchTableTileEntity.java:64) ~[primalmagick-4.0.9.jar%23753!/:4.0.9]
        at com.verdantartifice.primalmagick.common.tiles.base.AbstractTileSidedInventoryPM.getCapability(AbstractTileSidedInventoryPM.java:109) ~[primalmagick-4.0.9.jar%23753!/:4.0.9]
        at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33) ~[forge-1.20.1-47.2.20-universal.jar%23850!/:?]
        at net.minecraft.world.level.block.entity.BlockEntity.handler$zin000$onMarkDirty(BlockEntityMixin.java:1033) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.world.level.block.entity.BlockEntity.m_6596_(BlockEntityMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at com.verdantartifice.primalmagick.common.tiles.base.AbstractTileSidedInventoryPM.m_6596_(AbstractTileSidedInventoryPM.java:131) ~[primalmagick-4.0.9.jar%23753!/:4.0.9]
        at com.verdantartifice.primalmagick.common.capabilities.ItemStackHandlerPM.onContentsChanged(ItemStackHandlerPM.java:38) ~[primalmagick-4.0.9.jar%23753!/:4.0.9]
        at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:45) ~[forge-1.20.1-47.2.20-universal.jar%23850!/:?]
        at net.minecraftforge.items.SlotItemHandler.m_5866_(SlotItemHandler.java:83) ~[forge-1.20.1-47.2.20-universal.jar%23850!/:?]
        at net.minecraft.world.inventory.Slot.m_150656_(SlotMixin.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenuMixin.java:1118) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenuMixin.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23845!/:?]
        ... 17 more

**Comment by daedalus4096** [comment]
The bug you posted for the v4.0.9 version of Primal Magick should be fixed in v4.1.1, but you can only use that version of the mod with 1.20.2 of Minecraft. If you're going to stay on 1.20.1, then I'm afraid your only workaround is to keep your research table away from your Ars Nouveau table.
