### ISSUE TITLE
Failure during mod loading [1.21]

### ISSUE THREAD

**Issue by EpsilonZeroFive** [daedalus4096/PrimalMagick#291]
Versions 5.0.1 and 5.0.2 fail identically with the following exception:

Stacktrace:
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?] {}
-- MOD primalmagick --
Details:
	Mod File: /C:/Users/Powde/AppData/Roaming/.minecraft/mods/primalmagick-5.0.2-beta.jar
	Failure message: Primal Magick (primalmagick) has failed to load correctly
		java.lang.NoSuchMethodException: com.verdantartifice.primalmagick.PrimalMagick.<init>()
	Mod Version: 5.0.2-beta
	Mod Issue URL: https://github.com/daedalus4096/PrimalMagick/issues
	Exception message: java.lang.NoSuchMethodException: com.verdantartifice.primalmagick.PrimalMagick.<init>()
Stacktrace:
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?] {}
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?] {}
	at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.21-51.0.33/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.21-51.0.33.jar!/:51.0.33] {}
	at LAYER PLUGIN/net.minecraftforge.fmlcore@1.21-51.0.33/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.21-51.0.33.jar!/:1.0] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

If the mod is not to be made backward compatible with 1.21, it should be marked as such.
[crash-2024-09-30_18.13.12-fml.txt](https://github.com/user-attachments/files/17197434/crash-2024-09-30_18.13.12-fml.txt)

**Comment by daedalus4096** [comment]
Well, I had intended these two builds to remain backward compatible with 1.21, but after reviewing things I don't think that's going to work out. I'm going to remove the 1.21 marker from these builds, as I don't believe I can feasibly make them compatible with that version again, not without re-introducing serious bugs. Thank you for the report, and I apologize for the inconvenience.

**Comment by EpsilonZeroFive** [comment]
No worries, I'm glad I could help and alert you to the issue.
