### ISSUE TITLE
Spellcraft altar causes server to crash on placement, render, or use on version 2.0.6

### ISSUE THREAD

**Issue by norythumTDigEng** [daedalus4096/PrimalMagick#92]
after upgrade to latest version 2.0.6 existing altars can't be broken without causing server to crash. Performed a rollback to 2.0.5 and removed the altar. Performed upgrade again with all altars removed, upon placing altar server crashed. Same errors in both cases, error and crash report below:

java.lang.ExceptionInInitializerError: null
	at com.verdantartifice.primalmagick.common.tiles.crafting.SpellcraftingAltarTileEntity.<init>(SpellcraftingAltarTileEntity.java:43) ~[primalmagick-2.0.6.jar%23146!/:2.0.6] {re:classloading}
	at com.verdantartifice.primalmagick.common.blocks.crafting.SpellcraftingAltarBlock.m_142194_(SpellcraftingAltarBlock.java:100) ~[primalmagick-2.0.6.jar%23146!/:2.0.6] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:251) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_chunkclass,xf:fml:xaerominimap:xaero_chunkclass,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:supplementaries.mixins.json:LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:supplementaries.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:supplementaries.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:APP:supplementaries.mixins.json:BlockItemMixin,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.18.1-39.1.0-universal.jar%23187!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.ServerPlayerGameModeMixin,pl:mixin:APP:subpocket.mixins.json:ServerPlayerGameModeMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.verdantartifice.primalmagick.common.tiles.crafting.SpellcraftingAltarTileEntity$Segment.<clinit>(SpellcraftingAltarTileEntity.java:173) ~[primalmagick-2.0.6.jar%23146!/:2.0.6] {re:classloading}
	... 28 more

**Comment by daedalus4096** [comment]
This issue should be fixed as of version 2.0.7.  Please file a new ticket if you run across it again.  Thank you for the report!
